<?php
/*
Plugin Name: Formulário - Contato
Description: Plugin para gerenciar formulário de contato
Version: 1.0
Author: Maicon R. Santana
Author URI: http://www.maiconsantana.com.br
License: GPL


This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License, version 2, as 
published by the Free Software Foundation.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

GNU General Public License: http://www.gnu.org/licenses/gpl.html

*/

define('MRSOPTION', 'mrs_contact_018');

// Plugin Activation
/*function mrscontact_create_tables(){
    global $wpdb;
    require_once(ABSPATH . 'wp-admin/includes/upgrade.php');

    $table = $wpdb->prefix.'mrscontact';

    $sql_plugin = "CREATE TABLE `$table` (
		`id`  int(4) NOT NULL AUTO_INCREMENT ,
		`name`  varchar(255) NOT NULL ,
		`email`  varchar(255) NOT NULL ,
		`companion`  int(4) NOT NULL ,
		`confirm`  tinyint DEFAULT 1 ,
		`observation` text NULL ,
		`date`  timestamp NOT NULL ON UPDATE CURRENT_TIMESTAMP ,
		`file`  varchar(255) NULL ,
		`delete`  tinyint DEFAULT 0 ,
		PRIMARY KEY (`id`)
	);";
    dbDelta($sql_plugin);
}
register_deactivation_hook( __FILE__, 'mrscontact_create_tables' );
*/

// Add Menu 
function register_mrs_contact_menu() {
	add_menu_page('mensagens', 'Mensagens', 'publish_posts', dirname(__FILE__).'/index.php', '', 'dashicons-admin-comments', 6);
	add_submenu_page(dirname(__FILE__).'/index.php', 'vagas', 'Vagas', 'add_users', dirname(__FILE__).'/vagas.php' );
	add_submenu_page(dirname(__FILE__).'/index.php', 'contato', 'Contato', 'add_users', dirname(__FILE__).'/contato.php' );
}
add_action('admin_menu', 'register_mrs_contact_menu');


// Generate Subscribe Form 
function mrs_contact($atts=array()){

	// plugin script
	wp_enqueue_script( 'mrs_contact-script', plugin_dir_url( __FILE__ ) . 'files/scripts.js', array( 'jquery' ) );

	include('template/'.$atts['template'].'.php');

}
add_shortcode( 'mrs_contact', 'mrs_contact' );


//receber dados do formulario 
function mrs_contact_getForm()
{	
	//var_dump($_POST);
	//var_dump($_FILES);
	$post = $_POST;

	//validar arquivo
	if(isset($_FILES['curriculo']['name'])){
		$type = explode('.', $_FILES['curriculo']['name']);
		if($type['1'] != 'pdf'){
			//valida tipo de arquivo
			wp_redirect( $post['return'].'?envio=erro_anexo' );
			exit;
		};

		//envia arquivo
		if ( ! function_exists( 'wp_handle_upload' ) ) {
		    require_once( ABSPATH . 'wp-admin/includes/file.php' );
		}

		$uploadedfile = $_FILES['curriculo'];

		$upload_overrides = array( 'test_form' => false );

		$movefile = wp_handle_upload( $uploadedfile, $upload_overrides );

		if ( $movefile && ! isset( $movefile['error'] ) ) {
		    //echo "File is valid, and was successfully uploaded.\n";
		    //var_dump( $movefile );
		    $post['file'] = $movefile['url'];
		} else {
		    /**
		     * Error generated by _wp_handle_upload()
		     * @see _wp_handle_upload() in wp-admin/includes/file.php
		     */
		    //echo $movefile['error'];
		    wp_redirect( $post['return'].'?envio=erro_anexo' );
			exit;
		}
	}

	global $wpdb;

	//salvar no BD
	$tipo 		= isset($post['tipo']) ? $post['tipo'] : '';
	$assunto 	= isset($post['assunto']) ? 'Fale Conosco - '.$post['assunto'] : 'Trabalhe Conosco';
	$nome 		= isset($post['nome']) ? $post['nome'] : '';
	$email 		= isset($post['email']) ? $post['email'] : '';
	$news 		= isset($post['news']) ? $post['news'] : 0;
	$cargo 		= isset($post['cargo']) ? $post['cargo'] : ''; 
	$mensagem 	= isset($post['mensagem']) ? $post['mensagem'] : '';
	$telefone 	= isset($post['telefone']) ? $post['telefone'] : ''; 
	$empresa 	= isset($post['empresa']) ? $post['empresa'] : ''; 
	$file 		= isset($post['file']) ? $post['file'] : '';

	
	$table = $wpdb->prefix.'mrscontact';

	$sql = "insert into ".$table." (type, subject, name, email, cargo, message, phone, company, file, news, date) values ('".$tipo."', '".$assunto."', '".$nome."', '".$email."', '".$cargo."', '".$mensagem."', '".$telefone."', '".$empresa."', '".$file."', '".$news."', NOW() )";

	if( ! $wpdb->query($sql) ){
		echo 'erro';
		die();
	}
	
	// Inicializa o buffer e bloqueia qualquer saída para o navegador
	ob_start();

	//captar template email
	include('template/email_'.$tipo.'.php');

	$html = ob_get_contents();

	ob_end_clean();

	//buscar emails para envio
	$mail = json_decode(get_option(MRSOPTION));

	if($tipo == 'contato'){
		$to = $mail->email;
		$cc = $mail->email_cc;
	}else{
		$to = $mail->vg_email;
		$cc = $mail->vg_email_cc;
	}

	$header[] = 'Content-Type: text/html; charset=UTF-8';
	$header[] = 'From: '.wp_title().' <no-reply@almeidalaw.com.br>';
	
	if(!empty($cc)){
		$header[] = 'Cc: '.$cc;
	}

	//$header[] = 'Cco: registro-clientes@bluecommerce.com.br';
	$header[] = 'Reply-To: '.$email;

	$subject = $assunto;
	$message= $html;
	 
	$result = wp_mail( $to, $subject, $message, $header );

	if($result){
		wp_redirect( $post['return'].'?envio=sucesso' );
		exit;
	}else{
		wp_redirect( $post['return'].'?envio=erro' );
		exit;
	}

    die();
}
//Adiciona a funcao aos hooks ajax do WordPress.
add_action('wp_ajax_mrs_contact_getForm', 'mrs_contact_getForm');
add_action('wp_ajax_nopriv_mrs_contact_getForm', 'mrs_contact_getForm');


/*

// Salva dados
if ($_POST['amc_form']) {
	$nome 		= $_POST['amc_nome'];
	$email 		= $_POST['amc_email'];
	$comentario = $_POST['amc_comentario'];
	$pagina 	= $_POST['amc_pagina'];
	$data 		= date('Y-m-d');
		
	$wpdb->query("insert into ".$wpdb->prefix."amc (amc_nome, amc_email, amc_comentario, amc_pagina, amc_data) values ('".$nome."', '".$email."', '".$comentario."', '".$pagina."', '".$data."')");

}
*/
?>
